name: Publish Package and Docs

on:
  push:
    tags:
      - '*'

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - name: Clone our repository
      uses: actions/checkout@v2
    - name: Setup latest stable version of Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update pip
      run: pip install pip --upgrade
    - name: Install locally in dev mode bringing dev dependencies along
      run: pip install -e .[dev]
    - name: Test with pytest
      run: pytest

  publish:

    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Clone our repository
      uses: actions/checkout@v2
    - name: Setup latest stable version of Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
