name: Tests and test coverage

on:
  push:
    branches:
      - main

jobs:
  build-test-cov:

    runs-on: ubuntu-latest

    steps:
    - name: Clone our repository
      uses: actions/checkout@v2
    - name: Setup latest stable version of Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update pip
      run: pip install pip --upgrade
    - name: Install locally in dev mode bringing dev dependencies along
      run: pip install -e .[dev]
    - name: Test with pytest and create coverage report
      run: pytest --cov=finefibo --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        files: ./coverage.xml
